liip_imagine:
    resolvers:
       default:
          web_path: ~

    filter_sets:
        cache: ~
        video_fav_photo:
            quality: 80
            filters:
                thumbnail: { size: [150, 150], mode: outbound }
        prev_on_page_item_action:
            quality: 80
            filters:
                thumbnail: { size: [150, 150], mode: outbound }

        prev_on_page_item_slider_grid_2:
            quality: 85
            filters:
                thumbnail: { size: [170, 170], mode: outbound }

        prev_on_page_item_slider_grid_3:
            quality: 95
            filters:
                thumbnail: { size: [250, 250], mode: outbound }

        prev_on_page_item_slider_grid_4:
            quality: 95
            filters:
                thumbnail: { size: [250, 250], mode: outbound }

        prev_on_page_item_slider_grid_4_low:
            quality: 0
            filters:
                thumbnail: { size: [250, 250], mode: outbound }

        prev_on_page_item_slider_grid_3_low:
            quality: 0
            filters:
                thumbnail: { size: [250, 250], mode: outbound }

        prev_on_page_item_slider_grid_2_low:
            quality: 0
            filters:
                thumbnail: { size: [170, 170], mode: outbound }

        prev_on_page_item_slider:
            quality: 90
            filters:
                thumbnail: { size: [223, 223], mode: outbound }

        prev_on_window_item_slider:
            quality: 95
            filters:
                thumbnail: { size: [260, 260], mode: outbound }

        background_image:
            quality: 70
            filters:
                strip: ~

        full_size_photo_in_window:
            quality: 100
            filters:
                strip: ~