sonata_media:
    # if you don't use default namespace configuration
    class:
        media:              Application\Sonata\MediaBundle\Entity\Media
        gallery:            Application\Sonata\MediaBundle\Entity\Gallery
        gallery_has_media:  Application\Sonata\MediaBundle\Entity\GalleryHasMedia
    default_context: default
    db_driver: doctrine_orm
    providers:
        image:
            resizer: sonata.media.resizer.square
    contexts:
        default:  # the default context is mandatory
            download:
                strategy: sonata.media.security.superadmin_strategy
                mode: http
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file

            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}

        events_image:
            download:
                strategy: sonata.media.security.superadmin_strategy
                mode: http
            providers:
                  - sonata.media.provider.image
            formats:
                xsmall: { width: 80 , quality: 60}
                small: { width: 250 , quality: 70}
                medium: { width: 350 , quality: 85}
                big:   { width: 1000 , quality: 100}

        events_video:
            download:
                strategy: sonata.media.security.superadmin_strategy
                mode: http
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
            formats:
                small: { width: 250 , quality: 70}
                medium: { width: 550 , quality: 85}
                big:   { width: 1000 , quality: 100}

        blog_video:
            download:
                strategy: sonata.media.security.superadmin_strategy
                mode: http
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
            formats:
                small: { width: 250 , quality: 70}
                medium: { width: 550 , quality: 85}
                big:   { width: 1000 , quality: 100}
    cdn:
        server:
            path: /uploads/media # http://media.sonata-project.org/

    filesystem:
        local:
            directory:  %kernel.root_dir%/../web/uploads/media
            create:     true