bs_front_feedback:
    resource: "@BSFrontBundle/Resources/config/routing/feedback.yml"
    prefix:   /feedback

main:
    path:     /
    defaults: { _controller: BSFrontBundle:Default:index }

load_content:
    path:     /load/content/{entityType}/{id}
    defaults: { _controller: BSFrontBundle:Default:loadContent }

lazy_load_block_intro:
    path:     /lazy/load/intro
    defaults: { _controller: BSFrontBundle:Default:intro }

lazy_load_block_action:
    path:     /lazy/load/intro
    defaults: { _controller: BSFrontBundle:Default:action }