bs_front_event:
    resource: "@BSFrontBundle/Resources/config/routing/event.yml"
    prefix:   /event

bs_front_blog:
    resource: "@BSFrontBundle/Resources/config/routing/blog.yml"
    prefix:   /blog

main:
    path:     /
    defaults: { _controller: BSFrontBundle:Default:index }
