parameters:
#    bs_front.example.class: BS\FrontBundle\Example

services:
    app.twig_extension:
        class: BS\FrontBundle\Twig\AppExtension
        public: false
        tags:
            - { name: twig.extension }