<?php

namespace BS\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends EntityRepository
{
	public function findBySlug($slug)
	{
        $query = $this->createQueryBuilder("page")
            ->where('page.published = :is')
            ->andWhere('page.slug = :slug')
            ->setParameter('is', true)
            ->setParameter('slug', $slug)
            ->getQuery();

        return $query->getOneOrNullResult();
	}
}
